version: '3.8'
services:

  e-rr-posgresql:
    image: postgres:14.1
    container_name: e-rr-posgresql
    restart: always
    volumes:
      - e-rev-rate-service:/data/lib
    environment:
      - POSTGRES_DB=eRevRateServiceDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5435:5432'

volumes:
  e-rev-rate-service:
