spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/eRevRateServiceDB
    username: root
    password: toor
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
  redis:
    host: localhost
    port: 6379
    password: supersafepass!
    timeout: 2000

logging:
  level:
    ROOT: INFO
    com.midnightsun: DEBUG

server:
  port: 8084

global:
  exception-handling:
    debug-message: TRUE

info:
  application:
    name: RevRate Service
    version: 0.0.1
    description: Service managing reviews and ratings scores in eCart Application
